name: Publish Quarto

on:
  push:
    branches: [SCO]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup@v2

      - uses: actions/configure-pages@v5

      - run: quarto render

      - uses: actions/upload-pages-artifact@v3
        with:
          path: Build

      - uses: actions/deploy-pages@v4